import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'gr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    browseProperties: 'Browse Properties',
    sellProperty: 'Sell Property',
    allServices: 'All Services',
    submitProperty: 'List Your Property',
    callNow: 'Call Now',
    getStarted: 'Get Started',
    heroTitle: 'Find Your Dream Property',
    heroSubtitle: 'Discover exceptional properties with EliteHomes - where luxury meets innovation',
    exploreProperties: 'Explore Properties',
    featuredTitle: 'Featured Properties',
    featuredSubtitle: 'Discover our handpicked selection of premium properties',
    viewDetails: 'View Details',
    contactTitle: 'Get in Touch',
    contactSubtitle: 'Ready to find your dream property? Contact us today',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    sendMessage: 'Send Message',
    ourTeamNav: 'Our Team',
    topic: 'Topic',
    selectTopic: 'Select a topic',
    topicBuy: 'Buy',
    topicSell: 'Sell',
    topicRent: 'Rent',
    topicLegal: 'Legal Services',
    topicTechnical: 'Technical Services',
    topicOther: 'Other',
    howItWorksTitle: 'How It Works',
    step1Title: 'Schedule a Visit',
    step1Content: 'Browse our properties and schedule a viewing at your convenience',
    step2Title: 'Property Consultation',
    step2Content: 'Meet with our experts to discuss your needs and preferences',
    step3Title: 'Legal Review',
    step3Content: 'Our legal experts ensure all documentation is accurate and complete',
    step4Title: 'Complete Purchase',
    step4Content: 'Finalize the deal with our seamless closing process',
    teamTitle: 'Our People',
    teamSubtitle: 'The humans behind the code. Building with curiosity, caffeine, and quiet rebellion.',
    teamMember1Name: 'Maria Papadopoulos',
    teamMember1Role: 'Senior Property Consultant',
    teamMember1Tagline: 'Turning spaces into stories',
    teamMember1Bio: 'With over 15 years of experience in luxury real estate, Maria specializes in connecting clients with their perfect properties. She believes every home has a narrative waiting to be told.',
    teamMember1Department: 'Engineering',
    teamMember1LinkedIn: '#',
    teamMember2Name: 'Dimitris Kostas',
    teamMember2Role: 'Legal Advisor',
    teamMember2Tagline: 'Making contracts human-readable',
    teamMember2Bio: 'Expert in real estate law, ensuring every transaction is secure and compliant with all regulations. Dimitris demystifies legal jargon and protects your interests with precision.',
    teamMember2Department: 'Legal',
    teamMember2LinkedIn: '#',
    teamMember3Name: 'Elena Nikolaou',
    teamMember3Role: 'Marketing Director',
    teamMember3Tagline: 'Crafting narratives that sell',
    teamMember3Bio: 'Passionate about showcasing properties in their best light through innovative marketing strategies. Elena combines data-driven insights with creative storytelling to maximize property visibility.',
    teamMember3Department: 'Design',
    teamMember3LinkedIn: '#',
    teamMember4Name: 'Alexandros Dimitriou',
    teamMember4Role: 'Technical Operations',
    teamMember4Tagline: 'Building systems that scale',
    teamMember4Bio: 'Ensures seamless operations and technical excellence across all platforms. Alex automates the boring stuff so the team can focus on what matters—our clients.',
    teamMember4Department: 'Operations',
    teamMember4LinkedIn: '#',
    teamMember5Name: 'Sofia Andreou',
    teamMember5Role: 'Chief Architect',
    teamMember5Tagline: 'Designing tomorrow, today',
    teamMember5Bio: 'Leads architectural vision with a focus on sustainable innovation. Sofia believes great design is invisible until you need it—then it\'s everything.',
    teamMember5Department: 'Engineering',
    teamMember5LinkedIn: '#',
    teamMember6Name: 'Nikos Pavlou',
    teamMember6Role: 'Client Experience Lead',
    teamMember6Tagline: 'Your advocate, always',
    teamMember6Bio: 'Dedicated to ensuring every client journey exceeds expectations. Nikos knows that great service isn\'t just about solving problems—it\'s about anticipating them.',
    teamMember6Department: 'Operations',
    teamMember6LinkedIn: '#',
    
    // Sell Property Page
    sellPageTitle: 'Sell Your Property',
    sellPageMeta: 'Get the best value for your property with our expert team and innovative marketing',
    sellHeroTitle: 'Sell Your Property with Confidence',
    sellHeroSubtitle: 'Maximize your property\'s value with our comprehensive marketing and expert guidance. We handle everything from listing to closing.',
    createListing: 'Create Your Listing',
    talkToExpert: 'Talk to an Expert',
    
    // Why Sell With Us
    whySellTitle: 'Why Sell With Us',
    whySellSubtitle: 'Experience the difference of working with property marketing specialists',
    valueCard1Title: 'Showcase Real Value',
    valueCard1Desc: 'Professional photography, virtual tours, and compelling descriptions that highlight your property\'s unique features',
    valueCard2Title: 'Digital Marketing Experts',
    valueCard2Desc: 'Targeted campaigns across multiple channels to reach qualified buyers quickly',
    valueCard3Title: 'Specialist Team',
    valueCard3Desc: 'Legal and technical experts ensure smooth transactions and complete documentation',
    valueCard4Title: 'Seller-First Approach',
    valueCard4Desc: 'Your goals are our priority. We provide transparent updates and strategic advice throughout',
    
    // Create Listing Features
    listingFeaturesTitle: 'Create an Attractive Listing',
    listingFeaturesSubtitle: 'Stand out from the competition with our premium listing features',
    feature1Title: 'Stand-out Listing Design',
    feature1Desc: 'Eye-catching layouts that grab attention and showcase your property beautifully',
    feature2Title: 'Virtual Tour / 3D',
    feature2Desc: 'Immersive 3D walkthroughs that let buyers explore from anywhere',
    feature3Title: 'Independent Valuation',
    feature3Desc: 'Professional property valuation to ensure optimal pricing',
    feature4Title: 'Area Insights',
    feature4Desc: 'Comprehensive neighborhood data that adds value to your listing',
    
    // How It Works - Sell Page
    sellStepsTitle: 'How It Works',
    sellStepsSubtitle: 'Three simple steps to list your property',
    sellStep1Title: 'Enter Basic Details',
    sellStep1Desc: 'Fill in essential information about your property',
    sellStep2Title: 'Accept Terms',
    sellStep2Desc: 'Review and accept our brokerage agreement',
    sellStep3Title: 'Complete Listing',
    sellStep3Desc: 'Add photos and final details or schedule a call',
    
    // Form Fields
    ownerName: 'Owner Name',
    phone: 'Phone',
    propertyAddress: 'Property Address',
    propertyType: 'Property Type',
    apartment: 'Apartment',
    house: 'House',
    plot: 'Plot',
    commercial: 'Commercial',
    size: 'Size (m²)',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    parking: 'Parking',
    yes: 'Yes',
    no: 'No',
    yearBuilt: 'Year Built',
    condition: 'Condition',
    conditionNew: 'New',
    conditionRenovated: 'Renovated',
    conditionNeedsWork: 'Needs Work',
    askingPrice: 'Asking Price (€)',
    photos: 'Photos',
    uploadPhotos: 'Upload Photos',
    dragDropPhotos: 'Drag and drop photos here or click to browse',
    gdprConsent: 'I consent to the processing of my personal data in accordance with GDPR',
    acceptTerms: 'I accept the brokerage agreement terms',
    viewTerms: 'View Terms',
    nextStep: 'Next Step',
    previousStep: 'Previous',
    submitListing: 'Submit Listing',
    
    // Extended Fields
    floor: 'Floor',
    heatingType: 'Heating Type',
    energyClass: 'Energy Class',
    outdoorSpaces: 'Outdoor Spaces',
    view: 'View',
    renovationYear: 'Renovation Year',
    legalDocs: 'Legal Documents',
    technicalDocs: 'Technical Documents',
    uploadDocs: 'Upload Documents',
    scheduleCall: 'Schedule a Call',
    
    // Experts Block
    expertsTitle: 'Need Expert Guidance?',
    expertsSubtitle: 'Our property advisors are here to help you every step of the way',
    requestCall: 'Request a Call',
    
    // Photoshoot
    photoshootTitle: 'Professional Photoshoot Service',
    photoshootSubtitle: 'Make your property shine with our premium photography package',
    photoshoot1: 'High-resolution professional photography',
    photoshoot2: 'Interactive virtual tour technology',
    photoshoot3: 'Detailed floor plans and 3D renderings',
    bookPhotoshoot: 'Book Photoshoot',
    
    // FAQ
    faqTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Everything you need to know about selling with us',
    faq1Q: 'How long does it typically take to sell a property?',
    faq1A: 'The average time varies depending on location, price, and market conditions. Typically, well-priced properties in good condition sell within 2-4 months. Our marketing strategies are designed to attract qualified buyers quickly.',
    faq2Q: 'How do you determine the right price for my property?',
    faq2A: 'We provide a comprehensive market analysis considering recent comparable sales, current market trends, your property\'s unique features, and condition. We also offer independent professional valuation services.',
    faq3Q: 'What is the end-to-end process?',
    faq3A: 'First, we create your listing with professional photos and descriptions. Then we market your property across multiple channels. When we receive offers, we guide you through negotiations. Finally, our legal team handles all documentation through to completion.',
    faq4Q: 'Do I need to make repairs before selling?',
    faq4A: 'Not necessarily. We can advise on which improvements might increase value versus selling as-is. Minor improvements like fresh paint and decluttering often help, but major renovations may not always be worth the investment.',
    faq5Q: 'What documents are required?',
    faq5A: 'You\'ll need title deeds, energy certificate, building permit, property tax receipts, and any relevant technical studies. Our team will provide a complete checklist and can help arrange missing documents.',
    faq6Q: 'Do you provide legal and tax assistance?',
    faq6A: 'Yes, our specialist team includes legal and tax advisors who ensure all aspects of the sale comply with regulations and optimize your tax position.',
    faq7Q: 'Can buyers get financing through you?',
    faq7A: 'While we don\'t provide financing directly, we work with trusted financial partners and can connect buyers with suitable mortgage options.',
    faq8Q: 'How do I get started?',
    faq8A: 'Simply click "Create Your Listing" to fill in basic details, or "Talk to an Expert" to schedule a consultation. We\'ll guide you through every step.',
    
    // Promo Banner
    promoBannerText: 'Limited Time Offer: Free 3D Virtual Tour with every listing',
    promoBannerCta: 'Learn More',
    promoBannerUntil: 'Available until',
    promoBannerRegion: 'Athens & Thessaloniki regions only',
    
    // Success Page
    successTitle: 'Listing Submitted Successfully!',
    successMessage: 'Thank you for choosing us. Our team will review your listing and contact you within 24 hours.',
    successNextSteps: 'Next Steps',
    successStep1: 'Our team will review your submission',
    successStep2: 'We\'ll contact you to schedule a property visit',
    successStep3: 'Professional photos and listing creation',
    successStep4: 'Your property goes live on all channels',
    viewDashboard: 'View Dashboard',
    backToHome: 'Back to Home',
  },
  gr: {
    browseProperties: 'Αναζήτηση Ακινήτων',
    sellProperty: 'Πώληση Ακινήτου',
    allServices: 'Όλες οι Υπηρεσίες',
    submitProperty: 'Καταχώρηση Ακινήτου',
    callNow: 'Καλέστε Τώρα',
    getStarted: 'Ξεκινήστε',
    heroTitle: 'Βρείτε το Ιδανικό σας Ακίνητο',
    heroSubtitle: 'Ανακαλύψτε εξαιρετικά ακίνητα με την EliteHomes - όπου η πολυτέλεια συναντά την καινοτομία',
    exploreProperties: 'Εξερευνήστε Ακίνητα',
    featuredTitle: 'Επιλεγμένα Ακίνητα',
    featuredSubtitle: 'Ανακαλύψτε τα προσεκτικά επιλεγμένα premium ακίνητά μας',
    viewDetails: 'Λεπτομέρειες',
    contactTitle: 'Επικοινωνήστε',
    contactSubtitle: 'Έτοιμοι να βρείτε το ιδανικό σας ακίνητο; Επικοινωνήστε μαζί μας σήμερα',
    name: 'Όνομα',
    email: 'Email',
    message: 'Μήνυμα',
    sendMessage: 'Αποστολή Μηνύματος',
    ourTeamNav: 'Η Ομάδα Μας',
    topic: 'Θέμα',
    selectTopic: 'Επιλέξτε θέμα',
    topicBuy: 'Αγορά',
    topicSell: 'Πώληση',
    topicRent: 'Ενοικίαση',
    topicLegal: 'Νομικές Υπηρεσίες',
    topicTechnical: 'Τεχνικές Υπηρεσίες',
    topicOther: 'Άλλο',
    howItWorksTitle: 'Πώς Λειτουργεί',
    step1Title: 'Προγραμματίστε Επίσκεψη',
    step1Content: 'Περιηγηθείτε στα ακίνητά μας και προγραμματίστε μια προβολή όποτε σας βολεύει',
    step2Title: 'Συμβουλευτική Ακινήτου',
    step2Content: 'Συναντηθείτε με τους ειδικούς μας για να συζητήσετε τις ανάγκες και τις προτιμήσεις σας',
    step3Title: 'Νομική Επισκόπηση',
    step3Content: 'Οι νομικοί μας ειδικοί διασφαλίζουν ότι όλα τα έγγραφα είναι ακριβή και πλήρη',
    step4Title: 'Ολοκλήρωση Αγοράς',
    step4Content: 'Ολοκληρώστε τη συμφωνία με την απρόσκοπτη διαδικασία κλεισίματός μας',
    teamTitle: 'Οι Άνθρωποί Μας',
    teamSubtitle: 'Οι άνθρωποι πίσω από τον κώδικα. Χτίζουμε με περιέργεια, καφέ και ήσυχη επανάσταση.',
    teamMember1Name: 'Μαρία Παπαδοπούλου',
    teamMember1Role: 'Ανώτερη Σύμβουλος Ακινήτων',
    teamMember1Tagline: 'Μετατρέπουμε χώρους σε ιστορίες',
    teamMember1Bio: 'Με πάνω από 15 χρόνια εμπειρίας στα πολυτελή ακίνητα, η Μαρία ειδικεύεται στη σύνδεση πελατών με τα τέλεια ακίνητά τους. Πιστεύει ότι κάθε σπίτι έχει μια αφήγηση που περιμένει να λεχθεί.',
    teamMember1Department: 'Μηχανικοί',
    teamMember1LinkedIn: '#',
    teamMember2Name: 'Δημήτρης Κώστας',
    teamMember2Role: 'Νομικός Σύμβουλος',
    teamMember2Tagline: 'Κάνουμε τα συμβόλαια ανθρώπινα',
    teamMember2Bio: 'Ειδικός στο δίκαιο ακινήτων, διασφαλίζοντας ότι κάθε συναλλαγή είναι ασφαλής και σύμφωνη με όλους τους κανονισμούς. Ο Δημήτρης απομυθοποιεί τη νομική ορολογία και προστατεύει τα συμφέροντά σας με ακρίβεια.',
    teamMember2Department: 'Νομικά',
    teamMember2LinkedIn: '#',
    teamMember3Name: 'Έλενα Νικολάου',
    teamMember3Role: 'Διευθύντρια Marketing',
    teamMember3Tagline: 'Δημιουργούμε αφηγήσεις που πωλούν',
    teamMember3Bio: 'Παθιασμένη με την προβολή ακινήτων στο καλύτερο φως μέσω καινοτόμων στρατηγικών μάρκετινγκ. Η Έλενα συνδυάζει data-driven ιδέες με δημιουργική αφήγηση για μέγιστη ορατότητα.',
    teamMember3Department: 'Σχεδιασμός',
    teamMember3LinkedIn: '#',
    teamMember4Name: 'Αλέξανδρος Δημητρίου',
    teamMember4Role: 'Τεχνικές Λειτουργίες',
    teamMember4Tagline: 'Χτίζουμε συστήματα που κλιμακώνονται',
    teamMember4Bio: 'Διασφαλίζει απρόσκοπτες λειτουργίες και τεχνική αριστεία σε όλες τις πλατφόρμες. Ο Αλέξανδρος αυτοματοποιεί τα βαρετά για να επικεντρωθούμε σε αυτό που μετράει—τους πελάτες μας.',
    teamMember4Department: 'Λειτουργίες',
    teamMember4LinkedIn: '#',
    teamMember5Name: 'Σοφία Ανδρέου',
    teamMember5Role: 'Αρχιτέκτων Επικεφαλής',
    teamMember5Tagline: 'Σχεδιάζοντας το αύριο, σήμερα',
    teamMember5Bio: 'Ηγείται του αρχιτεκτονικού οράματος με επίκεντρο τη βιώσιμη καινοτομία. Η Σοφία πιστεύει ότι ο μεγάλος σχεδιασμός είναι αόρατος μέχρι να τον χρειαστείς—και τότε είναι τα πάντα.',
    teamMember5Department: 'Μηχανικοί',
    teamMember5LinkedIn: '#',
    teamMember6Name: 'Νίκος Παύλου',
    teamMember6Role: 'Υπεύθυνος Εμπειρίας Πελάτη',
    teamMember6Tagline: 'Ο υπερασπιστής σας, πάντα',
    teamMember6Bio: 'Αφοσιωμένος στο να διασφαλίσει ότι κάθε ταξίδι πελάτη ξεπερνά τις προσδοκίες. Ο Νίκος ξέρει ότι η εξαιρετική εξυπηρέτηση δεν είναι απλώς η επίλυση προβλημάτων—είναι η πρόβλεψή τους.',
    teamMember6Department: 'Λειτουργίες',
    teamMember6LinkedIn: '#',
    
    // Sell Property Page
    sellPageTitle: 'Πώληση Ακινήτου',
    sellPageMeta: 'Λάβετε την καλύτερη αξία για το ακίνητό σας με την ειδική ομάδα μας και καινοτόμο μάρκετινγκ',
    sellHeroTitle: 'Πωλήστε το Ακίνητό σας με Εμπιστοσύνη',
    sellHeroSubtitle: 'Μεγιστοποιήστε την αξία του ακινήτου σας με την ολοκληρωμένη προβολή μας και την καθοδήγηση ειδικών. Αναλαμβάνουμε τα πάντα από την καταχώρηση μέχρι την ολοκλήρωση.',
    createListing: 'Δημιουργήστε Καταχώρηση',
    talkToExpert: 'Μιλήστε με Ειδικό',
    
    // Why Sell With Us
    whySellTitle: 'Γιατί να Πουλήσετε Μαζί Μας',
    whySellSubtitle: 'Βιώστε τη διαφορά της συνεργασίας με ειδικούς στο μάρκετινγκ ακινήτων',
    valueCard1Title: 'Αναδεικνύουμε την Αληθινή Αξία',
    valueCard1Desc: 'Επαγγελματική φωτογράφηση, εικονικές περιηγήσεις και συναρπαστικές περιγραφές που αναδεικνύουν τα μοναδικά χαρακτηριστικά του ακινήτου σας',
    valueCard2Title: 'Ειδικοί Ψηφιακού Marketing',
    valueCard2Desc: 'Στοχευμένες καμπάνιες σε πολλαπλά κανάλια για να φτάσουμε γρήγορα σε κατάλληλους αγοραστές',
    valueCard3Title: 'Ομάδα Ειδικών',
    valueCard3Desc: 'Νομικοί και τεχνικοί ειδικοί διασφαλίζουν ομαλές συναλλαγές και πλήρη τεκμηρίωση',
    valueCard4Title: 'Προσέγγιση που Δίνει Προτεραιότητα στον Πωλητή',
    valueCard4Desc: 'Οι στόχοι σας είναι προτεραιότητά μας. Παρέχουμε διαφανείς ενημερώσεις και στρατηγικές συμβουλές',
    
    // Create Listing Features
    listingFeaturesTitle: 'Δημιουργήστε Ελκυστική Καταχώρηση',
    listingFeaturesSubtitle: 'Ξεχωρίστε από τον ανταγωνισμό με τις premium δυνατότητες καταχώρησης',
    feature1Title: 'Εντυπωσιακός Σχεδιασμός',
    feature1Desc: 'Εντυπωσιακές διατάξεις που προσελκύουν προσοχή και παρουσιάζουν όμορφα το ακίνητό σας',
    feature2Title: 'Εικονική Περιήγηση / 3D',
    feature2Desc: 'Καθηλωτικές 3D περιηγήσεις που επιτρέπουν στους αγοραστές να εξερευνήσουν από οπουδήποτε',
    feature3Title: 'Ανεξάρτητη Εκτίμηση',
    feature3Desc: 'Επαγγελματική εκτίμηση ακινήτου για βέλτιστη τιμολόγηση',
    feature4Title: 'Στοιχεία Περιοχής',
    feature4Desc: 'Ολοκληρωμένα δεδομένα γειτονιάς που προσθέτουν αξία στην καταχώρησή σας',
    
    // How It Works - Sell Page
    sellStepsTitle: 'Πώς Λειτουργεί',
    sellStepsSubtitle: 'Τρία απλά βήματα για να καταχωρήσετε το ακίνητό σας',
    sellStep1Title: 'Εισάγετε Βασικές Πληροφορίες',
    sellStep1Desc: 'Συμπληρώστε τις απαραίτητες πληροφορίες για το ακίνητό σας',
    sellStep2Title: 'Αποδοχή Όρων',
    sellStep2Desc: 'Ελέγξτε και αποδεχτείτε τη συμφωνία μεσιτείας μας',
    sellStep3Title: 'Ολοκλήρωση Καταχώρησης',
    sellStep3Desc: 'Προσθέστε φωτογραφίες και τελικές λεπτομέρειες ή προγραμματίστε κλήση',
    
    // Form Fields
    ownerName: 'Όνομα Ιδιοκτήτη',
    phone: 'Τηλέφωνο',
    propertyAddress: 'Διεύθυνση Ακινήτου',
    propertyType: 'Τύπος Ακινήτου',
    apartment: 'Διαμέρισμα',
    house: 'Μονοκατοικία',
    plot: 'Οικόπεδο',
    commercial: 'Επαγγελματικό',
    size: 'Μέγεθος (τ.μ.)',
    bedrooms: 'Υπνοδωμάτια',
    bathrooms: 'Μπάνια',
    parking: 'Χώρος Στάθμευσης',
    yes: 'Ναι',
    no: 'Όχι',
    yearBuilt: 'Έτος Κατασκευής',
    condition: 'Κατάσταση',
    conditionNew: 'Νέο',
    conditionRenovated: 'Ανακαινισμένο',
    conditionNeedsWork: 'Χρειάζεται Εργασίες',
    askingPrice: 'Τιμή Ζητούμενη (€)',
    photos: 'Φωτογραφίες',
    uploadPhotos: 'Μεταφόρτωση Φωτογραφιών',
    dragDropPhotos: 'Σύρετε και αποθέστε φωτογραφίες εδώ ή κάντε κλικ για αναζήτηση',
    gdprConsent: 'Συναινώ στην επεξεργασία των προσωπικών μου δεδομένων σύμφωνα με το GDPR',
    acceptTerms: 'Αποδέχομαι τους όρους της σύμβασης μεσιτείας',
    viewTerms: 'Προβολή Όρων',
    nextStep: 'Επόμενο Βήμα',
    previousStep: 'Προηγούμενο',
    submitListing: 'Υποβολή Καταχώρησης',
    
    // Extended Fields
    floor: 'Όροφος',
    heatingType: 'Τύπος Θέρμανσης',
    energyClass: 'Ενεργειακή Κλάση',
    outdoorSpaces: 'Εξωτερικοί Χώροι',
    view: 'Θέα',
    renovationYear: 'Έτος Ανακαίνισης',
    legalDocs: 'Νομικά Έγγραφα',
    technicalDocs: 'Τεχνικά Έγγραφα',
    uploadDocs: 'Μεταφόρτωση Εγγράφων',
    scheduleCall: 'Προγραμματισμός Κλήσης',
    
    // Experts Block
    expertsTitle: 'Χρειάζεστε Καθοδήγηση Ειδικού;',
    expertsSubtitle: 'Οι σύμβουλοι ακινήτων μας είναι εδώ να σας βοηθήσουν σε κάθε βήμα',
    requestCall: 'Αίτημα Κλήσης',
    
    // Photoshoot
    photoshootTitle: 'Υπηρεσία Επαγγελματικής Φωτογράφησης',
    photoshootSubtitle: 'Κάντε το ακίνητό σας να λάμψει με το premium πακέτο φωτογράφησης',
    photoshoot1: 'Επαγγελματική φωτογράφηση υψηλής ανάλυσης',
    photoshoot2: 'Διαδραστική τεχνολογία εικονικής περιήγησης',
    photoshoot3: 'Λεπτομερή κατόψεις και 3D αποδόσεις',
    bookPhotoshoot: 'Κράτηση Φωτογράφησης',
    
    // FAQ
    faqTitle: 'Συχνές Ερωτήσεις',
    faqSubtitle: 'Όλα όσα χρειάζεται να γνωρίζετε για την πώληση μαζί μας',
    faq1Q: 'Πόσος χρόνος χρειάζεται συνήθως για να πωληθεί ένα ακίνητο;',
    faq1A: 'Ο μέσος χρόνος ποικίλλει ανάλογα με την τοποθεσία, την τιμή και τις συνθήκες της αγοράς. Συνήθως, ακίνητα με σωστή τιμή και σε καλή κατάσταση πωλούνται εντός 2-4 μηνών. Οι στρατηγικές μάρκετινγκ μας έχουν σχεδιαστεί για να προσελκύουν γρήγορα κατάλληλους αγοραστές.',
    faq2Q: 'Πώς προσδιορίζετε τη σωστή τιμή για το ακίνητό μου;',
    faq2A: 'Παρέχουμε ολοκληρωμένη ανάλυση αγοράς λαμβάνοντας υπόψη πρόσφατες συγκρίσιμες πωλήσεις, τρέχουσες τάσεις της αγοράς, τα μοναδικά χαρακτηριστικά του ακινήτου σας και την κατάσταση. Προσφέρουμε επίσης ανεξάρτητες επαγγελματικές υπηρεσίες εκτίμησης.',
    faq3Q: 'Ποια είναι η διαδικασία από την αρχή μέχρι το τέλος;',
    faq3A: 'Αρχικά, δημιουργούμε την καταχώρησή σας με επαγγελματικές φωτογραφίες και περιγραφές. Στη συνέχεια, προβάλλουμε το ακίνητό σας σε πολλαπλά κανάλια. Όταν λάβουμε προσφορές, σας καθοδηγούμε στις διαπραγματεύσεις. Τέλος, η νομική μας ομάδα χειρίζεται όλα τα έγγραφα μέχρι την ολοκλήρωση.',
    faq4Q: 'Πρέπει να κάνω επισκευές πριν την πώληση;',
    faq4A: 'Όχι απαραίτητα. Μπορούμε να συμβουλεύσουμε για το ποιες βελτιώσεις μπορεί να αυξήσουν την αξία έναντι της πώλησης ως έχει. Μικρές βελτιώσεις όπως φρέσκο βάψιμο και αποκαθαρισμός συχνά βοηθούν, αλλά μεγάλες ανακαινίσεις μπορεί να μην αξίζουν πάντα την επένδυση.',
    faq5Q: 'Ποια έγγραφα απαιτούνται;',
    faq5A: 'Θα χρειαστείτε τίτλους ιδιοκτησίας, ενεργειακό πιστοποιητικό, οικοδομική άδεια, αποδείξεις φόρου ακινήτου και τυχόν σχετικές τεχνικές μελέτες. Η ομάδα μας θα παράσχει πλήρη λίστα ελέγχου και μπορεί να βοηθήσει στην εξασφάλιση των εγγράφων που λείπουν.',
    faq6Q: 'Παρέχετε νομική και φορολογική βοήθεια;',
    faq6A: 'Ναι, η ειδική ομάδα μας περιλαμβάνει νομικούς και φορολογικούς συμβούλους που διασφαλίζουν ότι όλες οι πτυχές της πώλησης συμμορφώνονται με τους κανονισμούς και βελτιστοποιούν τη φορολογική σας θέση.',
    faq7Q: 'Μπορούν οι αγοραστές να λάβουν χρηματοδότηση μέσω σας;',
    faq7A: 'Ενώ δεν παρέχουμε χρηματοδότηση απευθείας, συνεργαζόμαστε με αξιόπιστους χρηματοοικονομικούς συνεργάτες και μπορούμε να συνδέσουμε αγοραστές με κατάλληλες επιλογές στεγαστικού δανείου.',
    faq8Q: 'Πώς ξεκινώ;',
    faq8A: 'Απλά κάντε κλικ στο "Δημιουργήστε Καταχώρηση" για να συμπληρώσετε βασικές πληροφορίες, ή "Μιλήστε με Ειδικό" για να προγραμματίσετε συνάντηση. Θα σας καθοδηγήσουμε σε κάθε βήμα.',
    
    // Promo Banner
    promoBannerText: 'Προσφορά Περιορισμένου Χρόνου: Δωρεάν 3D Εικονική Περιήγηση με κάθε καταχώρηση',
    promoBannerCta: 'Μάθετε Περισσότερα',
    promoBannerUntil: 'Διαθέσιμο μέχρι',
    promoBannerRegion: 'Μόνο για περιοχές Αθήνας & Θεσσαλονίκης',
    
    // Success Page
    successTitle: 'Η Καταχώρηση Υποβλήθηκε Επιτυχώς!',
    successMessage: 'Σας ευχαριστούμε που μας επιλέξατε. Η ομάδα μας θα ελέγξει την καταχώρησή σας και θα επικοινωνήσει μαζί σας εντός 24 ωρών.',
    successNextSteps: 'Επόμενα Βήματα',
    successStep1: 'Η ομάδα μας θα ελέγξει την υποβολή σας',
    successStep2: 'Θα επικοινωνήσουμε για να προγραμματίσουμε επίσκεψη στο ακίνητο',
    successStep3: 'Επαγγελματικές φωτογραφίες και δημιουργία καταχώρησης',
    successStep4: 'Το ακίνητό σας δημοσιεύεται σε όλα τα κανάλια',
    viewDashboard: 'Προβολή Dashboard',
    backToHome: 'Επιστροφή στην Αρχική',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
