import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'gr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    browseProperties: 'Browse Properties',
    sellProperty: 'Sell Property',
    allServices: 'All Services',
    submitProperty: 'List Your Property',
    callNow: 'Call Now',
    getStarted: 'Get Started',
    heroTitle: 'Find Your Dream Property',
    heroSubtitle: 'Discover exceptional properties with EliteHomes - where luxury meets innovation',
    exploreProperties: 'Explore Properties',
    heroHeadline: 'Buy & Sell Property with Complete Confidence',
    heroSubheadline: 'Proper Land offers comprehensive services for buying, selling and managing properties with valuation, legal, technical and financing support. Everything in one place.',
    heroCtaPrimary: 'Start Your Search',
    heroCtaSecondary: 'Explore Services',
    heroTrustBadge: 'Certified Real Estate Advisors',
    heroStatsProperties: 'Available Properties',
    heroStatsSatisfaction: 'Client Satisfaction',
    heroStatsVolume: 'Transaction Value',
    featuredTitle: 'Featured Properties',
    featuredSubtitle: 'Discover our handpicked selection of premium properties',
    viewDetails: 'View Details',
    contactTitle: 'Get in Touch',
    contactSubtitle: 'Ready to find your dream property? Contact us today',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    sendMessage: 'Send Message',
    ourTeamNav: 'Our Team',
    topic: 'Topic',
    selectTopic: 'Select a topic',
    topicBuy: 'Buy',
    topicSell: 'Sell',
    topicRent: 'Rent',
    topicLegal: 'Legal Services',
    topicTechnical: 'Technical Services',
    topicOther: 'Other',
    howItWorksTitle: 'How It Works',
    step1Title: 'Schedule a Visit',
    step1Content: 'Browse our properties and schedule a viewing at your convenience',
    step2Title: 'Property Consultation',
    step2Content: 'Meet with our experts to discuss your needs and preferences',
    step3Title: 'Legal Review',
    step3Content: 'Our legal experts ensure all documentation is accurate and complete',
    step4Title: 'Complete Purchase',
    step4Content: 'Finalize the deal with our seamless closing process',
    teamTitle: 'Our People',
    teamSubtitle: 'The humans behind the code. Building with curiosity, caffeine, and quiet rebellion.',
    teamMember1Name: 'Maria Papadopoulos',
    teamMember1Role: 'Senior Property Consultant',
    teamMember1Tagline: 'Turning spaces into stories',
    teamMember1Bio: 'With over 15 years of experience in luxury real estate, Maria specializes in connecting clients with their perfect properties. She believes every home has a narrative waiting to be told.',
    teamMember1Department: 'Engineering',
    teamMember1LinkedIn: '#',
    teamMember2Name: 'Dimitris Kostas',
    teamMember2Role: 'Legal Advisor',
    teamMember2Tagline: 'Making contracts human-readable',
    teamMember2Bio: 'Expert in real estate law, ensuring every transaction is secure and compliant with all regulations. Dimitris demystifies legal jargon and protects your interests with precision.',
    teamMember2Department: 'Legal',
    teamMember2LinkedIn: '#',
    teamMember3Name: 'Elena Nikolaou',
    teamMember3Role: 'Marketing Director',
    teamMember3Tagline: 'Crafting narratives that sell',
    teamMember3Bio: 'Passionate about showcasing properties in their best light through innovative marketing strategies. Elena combines data-driven insights with creative storytelling to maximize property visibility.',
    teamMember3Department: 'Design',
    teamMember3LinkedIn: '#',
    teamMember4Name: 'Alexandros Dimitriou',
    teamMember4Role: 'Technical Operations',
    teamMember4Tagline: 'Building systems that scale',
    teamMember4Bio: 'Ensures seamless operations and technical excellence across all platforms. Alex automates the boring stuff so the team can focus on what matters—our clients.',
    teamMember4Department: 'Operations',
    teamMember4LinkedIn: '#',
    teamMember5Name: 'Sofia Andreou',
    teamMember5Role: 'Chief Architect',
    teamMember5Tagline: 'Designing tomorrow, today',
    teamMember5Bio: 'Leads architectural vision with a focus on sustainable innovation. Sofia believes great design is invisible until you need it—then it\'s everything.',
    teamMember5Department: 'Engineering',
    teamMember5LinkedIn: '#',
    teamMember6Name: 'Nikos Pavlou',
    teamMember6Role: 'Client Experience Lead',
    teamMember6Tagline: 'Your advocate, always',
    teamMember6Bio: 'Dedicated to ensuring every client journey exceeds expectations. Nikos knows that great service isn\'t just about solving problems—it\'s about anticipating them.',
    teamMember6Department: 'Operations',
    teamMember6LinkedIn: '#',
    
    // Sell Property Page
    sellPageTitle: 'Sell Your Property',
    sellPageMeta: 'Get the best value for your property with our expert team and innovative marketing',
    sellHeroTitle: 'Sell Your Property with Confidence',
    sellHeroSubtitle: 'Maximize your property\'s value with our comprehensive marketing and expert guidance. We handle everything from listing to closing.',
    createListing: 'Create Your Listing',
    talkToExpert: 'Talk to an Expert',
    
    // Why Sell With Us
    whySellTitle: 'Why Sell With Us',
    whySellSubtitle: 'Experience the difference of working with property marketing specialists',
    valueCard1Title: 'Showcase Real Value',
    valueCard1Desc: 'Professional photography, virtual tours, and compelling descriptions that highlight your property\'s unique features',
    valueCard2Title: 'Digital Marketing Experts',
    valueCard2Desc: 'Targeted campaigns across multiple channels to reach qualified buyers quickly',
    valueCard3Title: 'Specialist Team',
    valueCard3Desc: 'Legal and technical experts ensure smooth transactions and complete documentation',
    valueCard4Title: 'Seller-First Approach',
    valueCard4Desc: 'Your goals are our priority. We provide transparent updates and strategic advice throughout',
    
    // Create Listing Features
    listingFeaturesTitle: 'Create an Attractive Listing',
    listingFeaturesSubtitle: 'Stand out from the competition with our premium listing features',
    feature1Title: 'Stand-out Listing Design',
    feature1Desc: 'Eye-catching layouts that grab attention and showcase your property beautifully',
    feature2Title: 'Virtual Tour / 3D',
    feature2Desc: 'Immersive 3D walkthroughs that let buyers explore from anywhere',
    feature3Title: 'Independent Valuation',
    feature3Desc: 'Professional property valuation to ensure optimal pricing',
    feature4Title: 'Area Insights',
    feature4Desc: 'Comprehensive neighborhood data that adds value to your listing',
    
    // How It Works - Sell Page
    sellStepsTitle: 'How It Works',
    sellStepsSubtitle: 'Three simple steps to list your property',
    sellStep1Title: 'Enter Basic Details',
    sellStep1Desc: 'Fill in essential information about your property',
    sellStep2Title: 'Accept Terms',
    sellStep2Desc: 'Review and accept our brokerage agreement',
    sellStep3Title: 'Complete Listing',
    sellStep3Desc: 'Add photos and final details or schedule a call',
    
    // Form Fields
    ownerName: 'Owner Name',
    phone: 'Phone',
    propertyAddress: 'Property Address',
    propertyType: 'Property Type',
    apartment: 'Apartment',
    house: 'House',
    plot: 'Plot',
    commercial: 'Commercial',
    size: 'Size (m²)',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    parking: 'Parking',
    yes: 'Yes',
    no: 'No',
    yearBuilt: 'Year Built',
    condition: 'Condition',
    conditionNew: 'New',
    conditionRenovated: 'Renovated',
    conditionNeedsWork: 'Needs Work',
    askingPrice: 'Asking Price (€)',
    photos: 'Photos',
    uploadPhotos: 'Upload Photos',
    dragDropPhotos: 'Drag and drop photos here or click to browse',
    gdprConsent: 'I consent to the processing of my personal data in accordance with GDPR',
    acceptTerms: 'I accept the brokerage agreement terms',
    viewTerms: 'View Terms',
    nextStep: 'Next Step',
    previousStep: 'Previous',
    submitListing: 'Submit Listing',
    
    // Extended Fields
    floor: 'Floor',
    heatingType: 'Heating Type',
    energyClass: 'Energy Class',
    outdoorSpaces: 'Outdoor Spaces',
    view: 'View',
    renovationYear: 'Renovation Year',
    legalDocs: 'Legal Documents',
    technicalDocs: 'Technical Documents',
    uploadDocs: 'Upload Documents',
    scheduleCall: 'Schedule a Call',
    
    // Experts Block
    expertsTitle: 'Need Expert Guidance?',
    expertsSubtitle: 'Our property advisors are here to help you every step of the way',
    requestCall: 'Request a Call',
    
    // Photoshoot
    photoshootTitle: 'Professional Photoshoot Service',
    photoshootSubtitle: 'Make your property shine with our premium photography package',
    photoshoot1: 'High-resolution professional photography',
    photoshoot2: 'Interactive virtual tour technology',
    photoshoot3: 'Detailed floor plans and 3D renderings',
    bookPhotoshoot: 'Book Photoshoot',
    
    // FAQ
    faqTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Everything you need to know about selling with us',
    faq1Q: 'How long does it typically take to sell a property?',
    faq1A: 'The average time varies depending on location, price, and market conditions. Typically, well-priced properties in good condition sell within 2-4 months. Our marketing strategies are designed to attract qualified buyers quickly.',
    faq2Q: 'How do you determine the right price for my property?',
    faq2A: 'We provide a comprehensive market analysis considering recent comparable sales, current market trends, your property\'s unique features, and condition. We also offer independent professional valuation services.',
    faq3Q: 'What is the end-to-end process?',
    faq3A: 'First, we create your listing with professional photos and descriptions. Then we market your property across multiple channels. When we receive offers, we guide you through negotiations. Finally, our legal team handles all documentation through to completion.',
    faq4Q: 'Do I need to make repairs before selling?',
    faq4A: 'Not necessarily. We can advise on which improvements might increase value versus selling as-is. Minor improvements like fresh paint and decluttering often help, but major renovations may not always be worth the investment.',
    faq5Q: 'What documents are required?',
    faq5A: 'You\'ll need title deeds, energy certificate, building permit, property tax receipts, and any relevant technical studies. Our team will provide a complete checklist and can help arrange missing documents.',
    faq6Q: 'Do you provide legal and tax assistance?',
    faq6A: 'Yes, our specialist team includes legal and tax advisors who ensure all aspects of the sale comply with regulations and optimize your tax position.',
    faq7Q: 'Can buyers get financing through you?',
    faq7A: 'While we don\'t provide financing directly, we work with trusted financial partners and can connect buyers with suitable mortgage options.',
    faq8Q: 'How do I get started?',
    faq8A: 'Simply click "Create Your Listing" to fill in basic details, or "Talk to an Expert" to schedule a consultation. We\'ll guide you through every step.',
    
    // Promo Banner
    promoBannerText: 'Limited Time Offer: Free 3D Virtual Tour with every listing',
    promoBannerCta: 'Learn More',
    promoBannerUntil: 'Available until',
    promoBannerRegion: 'Athens & Thessaloniki regions only',
    
    // Success Page
    successTitle: 'Listing Submitted Successfully!',
    successMessage: 'Thank you for choosing us. Our team will review your listing and contact you within 24 hours.',
    successNextSteps: 'Next Steps',
    successStep1: 'Our team will review your submission',
    successStep2: 'We\'ll contact you to schedule a property visit',
    successStep3: 'Professional photos and listing creation',
    successStep4: 'Your property goes live on all channels',
    viewDashboard: 'View Dashboard',
    backToHome: 'Back to Home',
    homeLink: 'Go to homepage',
    switchLanguage: 'Switch language',
    
    // Tools page - comprehensive
    tools: 'Tools',
    buyVsRentCalculator: 'Buy vs Rent Calculator',
    buyVsRentCalculatorDescription: 'Comprehensive comparison tool - What truly benefits you?',
    buyVsRentTitle: 'Buy vs Rent Comparison Tool',
    buyVsRentSubtitle: 'This tool helps you see, based on your own numbers, whether it\'s more beneficial to buy or rent. Takes 5 minutes.',
    disclaimer: '*ATTENTION: This tool does not constitute financial advice. It provides guidance aligned with your lifestyle and financial priorities.',
    stepProgress: 'Step {current} of {total}',
    previousStep: 'Previous',
    nextStep: 'Next',
    finishCalculation: 'See Results',
    step1Title: 'Lifestyle & Personal Priorities',
    step1Subtitle: '*Answer with Yes/No only',
    question: 'Question',
    answer: 'Answer',
    yes: 'Yes',
    no: 'No',
    lifestyle_q1: 'Do you feel this is the home where you could live for many years?',
    lifestyle_q2: 'Would you be satisfied staying in the same city/area for the next 10 years?',
    lifestyle_q3: 'Do you feel emotionally "attached" to your home or neighborhood?',
    lifestyle_q4: 'Would you prefer to stay in the same city, even with financial/professional reasons to move?',
    lifestyle_q5: 'Does your job require you to be permanently in the area where you live today?',
    lifestyle_q6: 'Would you prefer your current location, even if you could work remotely?',
    lifestyle_q7: 'Would you prefer living in your own home, even with less flexibility vs renting?',
    lifestyle_q8: 'Are you willing to take on the cost and care for home maintenance?',
    lifestyle_q9: 'Do you believe owning offers more security and is worth the investment?',
    lifestyle_q10: 'Would you prefer your own home, even if not the most financially advantageous?',
    lifestyleConclusion: 'Lifestyle Assessment',
    lifestyleScoreBuying: 'Your responses indicate strong preference for home ownership',
    lifestyleScoreRenting: 'Your responses indicate flexibility and preference for renting',
    lifestyleScoreNeutral: 'Your responses show balanced view between buying and renting',
    step2Title: 'Financial Data Collection',
    step2Subtitle: 'Enter your financial information accurately',
    financial_q1: 'What is your net monthly income (after taxes)?',
    financial_q2: 'What is your current or estimated monthly rent?',
    financial_q3: 'What is the total purchase price of the property?',
    financial_q4: 'What would be the monthly loan payment?',
    financial_q5: 'What is the total estimated annual ownership cost (maintenance, insurance, taxes)?',
    financial_q6: 'What monthly rent could you collect if you rented this property?',
    financial_q7: 'How much initial capital for purchasing the property?',
    financial_q8: 'How much monthly passive income do you receive?',
    step3Title: 'Calculations & Indicators',
    step3Subtitle: 'Based on your inputs, here are the key financial metrics',
    indicator_1_title: 'Total Monthly Cost of Homeownership',
    indicator_1_desc: 'Sum of loan payment, maintenance, insurance, taxes, etc.',
    indicator_2_title: 'Monthly Housing Cost Comparison',
    indicator_2_desc: 'Negative = renting benefits you. Positive doesn\'t always mean buying is wiser.',
    indicator_3_title: 'Income % for Housing (Buying)',
    indicator_3_desc: 'Over 40% is high financial burden.',
    indicator_4_title: 'Income % for Housing (Renting)',
    indicator_4_desc: 'Over 40% is high financial burden.',
    indicator_5_title: 'Profit/Loss if You Rent Your Owned Home',
    indicator_5_desc: 'Positive = rent exceeds expenses, you profit.',
    indicator_6_title: 'Price-to-Rent Ratio',
    indicator_6_desc: 'Lower is better for buying. Above 20 = renting favored.',
    step4Title: 'Conclusion',
    step4Subtitle: 'Comprehensive analysis based on all inputs',
    conclusion_1_title: 'Would renting your owned home yield net profit?',
    conclusion_2_title: 'Annual return % if you lease it?',
    conclusion_3_title: 'Based on Price-to-Rent, is ownership or renting more favorable?',
    conclusion_4_title: 'If you invested initial capital at 15% annual return for 10 years:',
    financialIndependenceRule: 'FINANCIAL INDEPENDENCE RULE:',
    financialIndependenceRuleText: 'If passive income doesn\'t cover ownership costs, don\'t buy to live in!',
    profitAnswer: 'Yes, net monthly profit of €{amount}',
    lossAnswer: 'No, monthly loss of €{amount}',
    breakEvenAnswer: 'Break even',
    returnRate: '{rate}% annual return',
    priceToRentConclusion: 'Ratio: {ratio} - {recommendation}',
    priceToRentFavorBuying: 'Homeownership more favorable',
    priceToRentFavorRenting: 'Renting more favorable',
    priceToRentNeutral: 'Relatively balanced',
    investmentProjection: '€{amount} (vs €{initial} initial)',
    startOver: 'Start Over',
    switchToDark: 'Switch to dark mode',
    switchToLight: 'Switch to light mode',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    pageNotFound: 'Oops! Page not found',
    pageNotFoundDesc: 'The page you\'re looking for doesn\'t exist or has been moved.',
    returnHome: 'Return to Home',
    servicesPageTitle: 'By your side at every step',
    servicesPageSubtitle: 'We ensure a smooth and transparent process, from inspection to transaction completion—stress-free.',
    servicesPageTagline: 'Legal, technical, and commercial coordination from one point.',
    legalTechnicalCheckTitle: 'Legal & Technical Inspection',
    legalTechnicalCheckDesc: 'We check titles, any liens/pending issues, and the technical/urban planning status, so you know exactly what you\'re acquiring.',
    legalTechnicalCheckFeature1: 'Title & lien check (land registry/mortgage registry)',
    legalTechnicalCheckFeature2: 'Urban planning compliance & unauthorized constructions',
    legalTechnicalCheckFeature3: 'Clear report of findings & risks',
    propertyFolderTitle: 'Property Folder Setup',
    propertyFolderDesc: 'We gather and organize all documents (titles, E9 forms, regularizations, Energy Certificates, etc.) for quick and secure signing.',
    propertyFolderFeature1: 'Document & deadline checklist',
    propertyFolderFeature2: 'Digital archiving, ready for notary',
    propertyFolderFeature3: 'Pending issues tracking',
    valuationReportTitle: 'Property Valuation Report',
    valuationReportDesc: 'We provide substantiated valuation with market comparables and demand analysis, for fair and realistic pricing.',
    valuationReportFeature1: 'Real-time & historical comparables',
    valuationReportFeature2: 'Area, demand & yield analysis',
    valuationReportFeature3: 'Transparent valuation methodology',
    professionalPhotographyTitle: 'Professional Photography Service',
    professionalPhotographyDesc: 'High-quality photography (and optionally floor plan/staging) for top-tier presentation in listings and social media.',
    professionalPhotographyFeature1: 'HDR photos & short video/REELS',
    professionalPhotographyFeature2: 'Floor plan & light virtual staging (optional)',
    professionalPhotographyFeature3: 'Optimized for portals & social media',
    startNow: 'Start Now',
    talkToAdvisor: 'Talk to Advisor',
    requestValuation: 'Request Valuation',
    bookAppointment: 'Book Appointment',
    readyToStart: 'Ready to get started? Request a customized quote today.',
    requestQuote: 'Request Quote',
  },
  gr: {
    browseProperties: 'Αναζήτηση Ακινήτων',
    sellProperty: 'Πώληση Ακινήτου',
    allServices: 'Όλες οι Υπηρεσίες',
    submitProperty: 'Καταχώρηση Ακινήτου',
    callNow: 'Καλέστε Τώρα',
    getStarted: 'Ξεκινήστε',
    heroTitle: 'Βρείτε το Ιδανικό σας Ακίνητο',
    heroSubtitle: 'Ανακαλύψτε εξαιρετικά ακίνητα με την EliteHomes - όπου η πολυτέλεια συναντά την καινοτομία',
    exploreProperties: 'Εξερευνήστε Ακίνητα',
    heroHeadline: 'Αγορά & Πώληση Ακινήτου με Απόλυτη Ασφάλεια',
    heroSubheadline: 'Η Proper Land προσφέρει ολοκληρωμένες υπηρεσίες για την αγορά ακινήτου, πώληση ακινήτου και διαχείριση με εκτίμηση, νομικό έλεγχο, τεχνικό έλεγχο και χρηματοδότηση. Όλα σε ένα μέρος.',
    heroCtaPrimary: 'Ξεκινήστε την Αναζήτησή σας',
    heroCtaSecondary: 'Εξερευνήστε τις Υπηρεσίες',
    heroTrustBadge: 'Πιστοποιημένοι Σύμβουλοι Ακινήτων',
    heroStatsProperties: 'Διαθέσιμα Ακίνητα',
    heroStatsSatisfaction: 'Ικανοποίηση Πελατών',
    heroStatsVolume: 'Αξία Συναλλαγών',
    featuredTitle: 'Επιλεγμένα Ακίνητα',
    featuredSubtitle: 'Ανακαλύψτε τα προσεκτικά επιλεγμένα premium ακίνητά μας',
    viewDetails: 'Λεπτομέρειες',
    contactTitle: 'Επικοινωνήστε',
    contactSubtitle: 'Έτοιμοι να βρείτε το ιδανικό σας ακίνητο; Επικοινωνήστε μαζί μας σήμερα',
    name: 'Όνομα',
    email: 'Email',
    message: 'Μήνυμα',
    sendMessage: 'Αποστολή Μηνύματος',
    ourTeamNav: 'Η Ομάδα Μας',
    topic: 'Θέμα',
    selectTopic: 'Επιλέξτε θέμα',
    topicBuy: 'Αγορά',
    topicSell: 'Πώληση',
    topicRent: 'Ενοικίαση',
    topicLegal: 'Νομικές Υπηρεσίες',
    topicTechnical: 'Τεχνικές Υπηρεσίες',
    topicOther: 'Άλλο',
    howItWorksTitle: 'Πώς Λειτουργεί',
    step1Title: 'Προγραμματίστε Επίσκεψη',
    step1Content: 'Περιηγηθείτε στα ακίνητά μας και προγραμματίστε μια προβολή όποτε σας βολεύει',
    step2Title: 'Συμβουλευτική Ακινήτου',
    step2Content: 'Συναντηθείτε με τους ειδικούς μας για να συζητήσετε τις ανάγκες και τις προτιμήσεις σας',
    step3Title: 'Νομική Επισκόπηση',
    step3Content: 'Οι νομικοί μας ειδικοί διασφαλίζουν ότι όλα τα έγγραφα είναι ακριβή και πλήρη',
    step4Title: 'Ολοκλήρωση Αγοράς',
    step4Content: 'Ολοκληρώστε τη συμφωνία με την απρόσκοπτη διαδικασία κλεισίματός μας',
    teamTitle: 'Οι Άνθρωποί Μας',
    teamSubtitle: 'Οι άνθρωποι πίσω από τον κώδικα. Χτίζουμε με περιέργεια, καφέ και ήσυχη επανάσταση.',
    teamMember1Name: 'Μαρία Παπαδοπούλου',
    teamMember1Role: 'Ανώτερη Σύμβουλος Ακινήτων',
    teamMember1Tagline: 'Μετατρέπουμε χώρους σε ιστορίες',
    teamMember1Bio: 'Με πάνω από 15 χρόνια εμπειρίας στα πολυτελή ακίνητα, η Μαρία ειδικεύεται στη σύνδεση πελατών με τα τέλεια ακίνητά τους. Πιστεύει ότι κάθε σπίτι έχει μια αφήγηση που περιμένει να λεχθεί.',
    teamMember1Department: 'Μηχανικοί',
    teamMember1LinkedIn: '#',
    teamMember2Name: 'Δημήτρης Κώστας',
    teamMember2Role: 'Νομικός Σύμβουλος',
    teamMember2Tagline: 'Κάνουμε τα συμβόλαια ανθρώπινα',
    teamMember2Bio: 'Ειδικός στο δίκαιο ακινήτων, διασφαλίζοντας ότι κάθε συναλλαγή είναι ασφαλής και σύμφωνη με όλους τους κανονισμούς. Ο Δημήτρης απομυθοποιεί τη νομική ορολογία και προστατεύει τα συμφέροντά σας με ακρίβεια.',
    teamMember2Department: 'Νομικά',
    teamMember2LinkedIn: '#',
    teamMember3Name: 'Έλενα Νικολάου',
    teamMember3Role: 'Διευθύντρια Marketing',
    teamMember3Tagline: 'Δημιουργούμε αφηγήσεις που πωλούν',
    teamMember3Bio: 'Παθιασμένη με την προβολή ακινήτων στο καλύτερο φως μέσω καινοτόμων στρατηγικών μάρκετινγκ. Η Έλενα συνδυάζει data-driven ιδέες με δημιουργική αφήγηση για μέγιστη ορατότητα.',
    teamMember3Department: 'Σχεδιασμός',
    teamMember3LinkedIn: '#',
    teamMember4Name: 'Αλέξανδρος Δημητρίου',
    teamMember4Role: 'Τεχνικές Λειτουργίες',
    teamMember4Tagline: 'Χτίζουμε συστήματα που κλιμακώνονται',
    teamMember4Bio: 'Διασφαλίζει απρόσκοπτες λειτουργίες και τεχνική αριστεία σε όλες τις πλατφόρμες. Ο Αλέξανδρος αυτοματοποιεί τα βαρετά για να επικεντρωθούμε σε αυτό που μετράει—τους πελάτες μας.',
    teamMember4Department: 'Λειτουργίες',
    teamMember4LinkedIn: '#',
    teamMember5Name: 'Σοφία Ανδρέου',
    teamMember5Role: 'Αρχιτέκτων Επικεφαλής',
    teamMember5Tagline: 'Σχεδιάζοντας το αύριο, σήμερα',
    teamMember5Bio: 'Ηγείται του αρχιτεκτονικού οράματος με επίκεντρο τη βιώσιμη καινοτομία. Η Σοφία πιστεύει ότι ο μεγάλος σχεδιασμός είναι αόρατος μέχρι να τον χρειαστείς—και τότε είναι τα πάντα.',
    teamMember5Department: 'Μηχανικοί',
    teamMember5LinkedIn: '#',
    teamMember6Name: 'Νίκος Παύλου',
    teamMember6Role: 'Υπεύθυνος Εμπειρίας Πελάτη',
    teamMember6Tagline: 'Ο υπερασπιστής σας, πάντα',
    teamMember6Bio: 'Αφοσιωμένος στο να διασφαλίσει ότι κάθε ταξίδι πελάτη ξεπερνά τις προσδοκίες. Ο Νίκος ξέρει ότι η εξαιρετική εξυπηρέτηση δεν είναι απλώς η επίλυση προβλημάτων—είναι η πρόβλεψή τους.',
    teamMember6Department: 'Λειτουργίες',
    teamMember6LinkedIn: '#',
    
    // Sell Property Page
    sellPageTitle: 'Πώληση Ακινήτου',
    sellPageMeta: 'Λάβετε την καλύτερη αξία για το ακίνητό σας με την ειδική ομάδα μας και καινοτόμο μάρκετινγκ',
    sellHeroTitle: 'Πωλήστε το Ακίνητό σας με Εμπιστοσύνη',
    sellHeroSubtitle: 'Μεγιστοποιήστε την αξία του ακινήτου σας με την ολοκληρωμένη προβολή μας και την καθοδήγηση ειδικών. Αναλαμβάνουμε τα πάντα από την καταχώρηση μέχρι την ολοκλήρωση.',
    createListing: 'Δημιουργήστε Καταχώρηση',
    talkToExpert: 'Μιλήστε με Ειδικό',
    
    // Why Sell With Us
    whySellTitle: 'Γιατί να Πουλήσετε Μαζί Μας',
    whySellSubtitle: 'Βιώστε τη διαφορά της συνεργασίας με ειδικούς στο μάρκετινγκ ακινήτων',
    valueCard1Title: 'Αναδεικνύουμε την Αληθινή Αξία',
    valueCard1Desc: 'Επαγγελματική φωτογράφηση, εικονικές περιηγήσεις και συναρπαστικές περιγραφές που αναδεικνύουν τα μοναδικά χαρακτηριστικά του ακινήτου σας',
    valueCard2Title: 'Ειδικοί Ψηφιακού Marketing',
    valueCard2Desc: 'Στοχευμένες καμπάνιες σε πολλαπλά κανάλια για να φτάσουμε γρήγορα σε κατάλληλους αγοραστές',
    valueCard3Title: 'Ομάδα Ειδικών',
    valueCard3Desc: 'Νομικοί και τεχνικοί ειδικοί διασφαλίζουν ομαλές συναλλαγές και πλήρη τεκμηρίωση',
    valueCard4Title: 'Προσέγγιση που Δίνει Προτεραιότητα στον Πωλητή',
    valueCard4Desc: 'Οι στόχοι σας είναι προτεραιότητά μας. Παρέχουμε διαφανείς ενημερώσεις και στρατηγικές συμβουλές',
    
    // Create Listing Features
    listingFeaturesTitle: 'Δημιουργήστε Ελκυστική Καταχώρηση',
    listingFeaturesSubtitle: 'Ξεχωρίστε από τον ανταγωνισμό με τις premium δυνατότητες καταχώρησης',
    feature1Title: 'Εντυπωσιακός Σχεδιασμός',
    feature1Desc: 'Εντυπωσιακές διατάξεις που προσελκύουν προσοχή και παρουσιάζουν όμορφα το ακίνητό σας',
    feature2Title: 'Εικονική Περιήγηση / 3D',
    feature2Desc: 'Καθηλωτικές 3D περιηγήσεις που επιτρέπουν στους αγοραστές να εξερευνήσουν από οπουδήποτε',
    feature3Title: 'Ανεξάρτητη Εκτίμηση',
    feature3Desc: 'Επαγγελματική εκτίμηση ακινήτου για βέλτιστη τιμολόγηση',
    feature4Title: 'Στοιχεία Περιοχής',
    feature4Desc: 'Ολοκληρωμένα δεδομένα γειτονιάς που προσθέτουν αξία στην καταχώρησή σας',
    
    // How It Works - Sell Page
    sellStepsTitle: 'Πώς Λειτουργεί',
    sellStepsSubtitle: 'Τρία απλά βήματα για να καταχωρήσετε το ακίνητό σας',
    sellStep1Title: 'Εισάγετε Βασικές Πληροφορίες',
    sellStep1Desc: 'Συμπληρώστε τις απαραίτητες πληροφορίες για το ακίνητό σας',
    sellStep2Title: 'Αποδοχή Όρων',
    sellStep2Desc: 'Ελέγξτε και αποδεχτείτε τη συμφωνία μεσιτείας μας',
    sellStep3Title: 'Ολοκλήρωση Καταχώρησης',
    sellStep3Desc: 'Προσθέστε φωτογραφίες και τελικές λεπτομέρειες ή προγραμματίστε κλήση',
    
    // Form Fields
    ownerName: 'Όνομα Ιδιοκτήτη',
    phone: 'Τηλέφωνο',
    propertyAddress: 'Διεύθυνση Ακινήτου',
    propertyType: 'Τύπος Ακινήτου',
    apartment: 'Διαμέρισμα',
    house: 'Μονοκατοικία',
    plot: 'Οικόπεδο',
    commercial: 'Επαγγελματικό',
    size: 'Μέγεθος (τ.μ.)',
    bedrooms: 'Υπνοδωμάτια',
    bathrooms: 'Μπάνια',
    parking: 'Χώρος Στάθμευσης',
    yes: 'Ναι',
    no: 'Όχι',
    yearBuilt: 'Έτος Κατασκευής',
    condition: 'Κατάσταση',
    conditionNew: 'Νέο',
    conditionRenovated: 'Ανακαινισμένο',
    conditionNeedsWork: 'Χρειάζεται Εργασίες',
    askingPrice: 'Τιμή Ζητούμενη (€)',
    photos: 'Φωτογραφίες',
    uploadPhotos: 'Μεταφόρτωση Φωτογραφιών',
    dragDropPhotos: 'Σύρετε και αποθέστε φωτογραφίες εδώ ή κάντε κλικ για αναζήτηση',
    gdprConsent: 'Συναινώ στην επεξεργασία των προσωπικών μου δεδομένων σύμφωνα με το GDPR',
    acceptTerms: 'Αποδέχομαι τους όρους της σύμβασης μεσιτείας',
    viewTerms: 'Προβολή Όρων',
    nextStep: 'Επόμενο Βήμα',
    previousStep: 'Προηγούμενο',
    submitListing: 'Υποβολή Καταχώρησης',
    
    // Extended Fields
    floor: 'Όροφος',
    heatingType: 'Τύπος Θέρμανσης',
    energyClass: 'Ενεργειακή Κλάση',
    outdoorSpaces: 'Εξωτερικοί Χώροι',
    view: 'Θέα',
    renovationYear: 'Έτος Ανακαίνισης',
    legalDocs: 'Νομικά Έγγραφα',
    technicalDocs: 'Τεχνικά Έγγραφα',
    uploadDocs: 'Μεταφόρτωση Εγγράφων',
    scheduleCall: 'Προγραμματισμός Κλήσης',
    
    // Experts Block
    expertsTitle: 'Χρειάζεστε Καθοδήγηση Ειδικού;',
    expertsSubtitle: 'Οι σύμβουλοι ακινήτων μας είναι εδώ να σας βοηθήσουν σε κάθε βήμα',
    requestCall: 'Αίτημα Κλήσης',
    
    // Photoshoot
    photoshootTitle: 'Υπηρεσία Επαγγελματικής Φωτογράφησης',
    photoshootSubtitle: 'Κάντε το ακίνητό σας να λάμψει με το premium πακέτο φωτογράφησης',
    photoshoot1: 'Επαγγελματική φωτογράφηση υψηλής ανάλυσης',
    photoshoot2: 'Διαδραστική τεχνολογία εικονικής περιήγησης',
    photoshoot3: 'Λεπτομερή κατόψεις και 3D αποδόσεις',
    bookPhotoshoot: 'Κράτηση Φωτογράφησης',
    
    // FAQ
    faqTitle: 'Συχνές Ερωτήσεις',
    faqSubtitle: 'Όλα όσα χρειάζεται να γνωρίζετε για την πώληση μαζί μας',
    faq1Q: 'Πόσος χρόνος χρειάζεται συνήθως για να πωληθεί ένα ακίνητο;',
    faq1A: 'Ο μέσος χρόνος ποικίλλει ανάλογα με την τοποθεσία, την τιμή και τις συνθήκες της αγοράς. Συνήθως, ακίνητα με σωστή τιμή και σε καλή κατάσταση πωλούνται εντός 2-4 μηνών. Οι στρατηγικές μάρκετινγκ μας έχουν σχεδιαστεί για να προσελκύουν γρήγορα κατάλληλους αγοραστές.',
    faq2Q: 'Πώς προσδιορίζετε τη σωστή τιμή για το ακίνητό μου;',
    faq2A: 'Παρέχουμε ολοκληρωμένη ανάλυση αγοράς λαμβάνοντας υπόψη πρόσφατες συγκρίσιμες πωλήσεις, τρέχουσες τάσεις της αγοράς, τα μοναδικά χαρακτηριστικά του ακινήτου σας και την κατάσταση. Προσφέρουμε επίσης ανεξάρτητες επαγγελματικές υπηρεσίες εκτίμησης.',
    faq3Q: 'Ποια είναι η διαδικασία από την αρχή μέχρι το τέλος;',
    faq3A: 'Αρχικά, δημιουργούμε την καταχώρησή σας με επαγγελματικές φωτογραφίες και περιγραφές. Στη συνέχεια, προβάλλουμε το ακίνητό σας σε πολλαπλά κανάλια. Όταν λάβουμε προσφορές, σας καθοδηγούμε στις διαπραγματεύσεις. Τέλος, η νομική μας ομάδα χειρίζεται όλα τα έγγραφα μέχρι την ολοκλήρωση.',
    faq4Q: 'Πρέπει να κάνω επισκευές πριν την πώληση;',
    faq4A: 'Όχι απαραίτητα. Μπορούμε να συμβουλεύσουμε για το ποιες βελτιώσεις μπορεί να αυξήσουν την αξία έναντι της πώλησης ως έχει. Μικρές βελτιώσεις όπως φρέσκο βάψιμο και αποκαθαρισμός συχνά βοηθούν, αλλά μεγάλες ανακαινίσεις μπορεί να μην αξίζουν πάντα την επένδυση.',
    faq5Q: 'Ποια έγγραφα απαιτούνται;',
    faq5A: 'Θα χρειαστείτε τίτλους ιδιοκτησίας, ενεργειακό πιστοποιητικό, οικοδομική άδεια, αποδείξεις φόρου ακινήτου και τυχόν σχετικές τεχνικές μελέτες. Η ομάδα μας θα παράσχει πλήρη λίστα ελέγχου και μπορεί να βοηθήσει στην εξασφάλιση των εγγράφων που λείπουν.',
    faq6Q: 'Παρέχετε νομική και φορολογική βοήθεια;',
    faq6A: 'Ναι, η ειδική ομάδα μας περιλαμβάνει νομικούς και φορολογικούς συμβούλους που διασφαλίζουν ότι όλες οι πτυχές της πώλησης συμμορφώνονται με τους κανονισμούς και βελτιστοποιούν τη φορολογική σας θέση.',
    faq7Q: 'Μπορούν οι αγοραστές να λάβουν χρηματοδότηση μέσω σας;',
    faq7A: 'Ενώ δεν παρέχουμε χρηματοδότηση απευθείας, συνεργαζόμαστε με αξιόπιστους χρηματοοικονομικούς συνεργάτες και μπορούμε να συνδέσουμε αγοραστές με κατάλληλες επιλογές στεγαστικού δανείου.',
    faq8Q: 'Πώς ξεκινώ;',
    faq8A: 'Απλά κάντε κλικ στο "Δημιουργήστε Καταχώρηση" για να συμπληρώσετε βασικές πληροφορίες, ή "Μιλήστε με Ειδικό" για να προγραμματίσετε συνάντηση. Θα σας καθοδηγήσουμε σε κάθε βήμα.',
    
    // Promo Banner
    promoBannerText: 'Προσφορά Περιορισμένου Χρόνου: Δωρεάν 3D Εικονική Περιήγηση με κάθε καταχώρηση',
    promoBannerCta: 'Μάθετε Περισσότερα',
    promoBannerUntil: 'Διαθέσιμο μέχρι',
    promoBannerRegion: 'Μόνο για περιοχές Αθήνας & Θεσσαλονίκης',
    
    // Success Page
    successTitle: 'Η Καταχώρηση Υποβλήθηκε Επιτυχώς!',
    successMessage: 'Σας ευχαριστούμε που μας επιλέξατε. Η ομάδα μας θα ελέγξει την καταχώρησή σας και θα επικοινωνήσει μαζί σας εντός 24 ωρών.',
    successNextSteps: 'Επόμενα Βήματα',
    successStep1: 'Η ομάδα μας θα ελέγξει την υποβολή σας',
    successStep2: 'Θα επικοινωνήσουμε για να προγραμματίσουμε επίσκεψη στο ακίνητο',
    successStep3: 'Επαγγελματικές φωτογραφίες και δημιουργία καταχώρησης',
    successStep4: 'Το ακίνητό σας δημοσιεύεται σε όλα τα κανάλια',
    viewDashboard: 'Προβολή Dashboard',
    backToHome: 'Επιστροφή στην Αρχική',
    homeLink: 'Μετάβαση στην αρχική',
    switchLanguage: 'Αλλαγή γλώσσας',
    
    // Tools Page - Greek translations
    tools: 'Εργαλεία',
    buyVsRentCalculator: 'Υπολογιστής Αγοράς vs Ενοικίασης',
    buyVsRentCalculatorDescription: 'Ολοκληρωμένο εργαλείο σύγκρισης - Τι σε συμφέρει πραγματικά;',
    buyVsRentTitle: 'Εργαλείο Σύγκρισης Αγοράς vs Ενοικίασης',
    buyVsRentSubtitle: 'Αυτό το εργαλείο σε βοηθά να δεις, με βάση τα δικά σου νούμερα, αν σε συμφέρει περισσότερο να αγοράσεις ή να νοικιάζεις. Θα χρειαστείς 5 λεπτά.',
    disclaimer: '*ΠΡΟΣΟΧΗ: Το εργαλείο δεν αποτελεί οικονομική συμβουλή. Σου προσφέρει μια ενδεικτική εικόνα για το αν η επιλογή σου είναι ευθυγραμμισμένη με τον τρόπο ζωής και τις οικονομικές σου προτεραιότητες.',
    stepProgress: 'Βήμα {current} από {total}',
    previousStep: 'Προηγούμενο',
    nextStep: 'Επόμενο',
    finishCalculation: 'Δες Αποτελέσματα',
    step1Title: 'Lifestyle & Προσωπικές Προτεραιότητες',
    step1Subtitle: '*Απάντησε μόνο με Ναι/Όχι',
    question: 'Ερώτηση',
    answer: 'Απάντηση',
    yes: 'Ναι',
    no: 'Όχι',
    lifestyle_q1: 'Νιώθεις ότι αυτό είναι το σπίτι όπου θα μπορούσες να ζήσεις για πολλά χρόνια;',
    lifestyle_q2: 'Θα σε ικανοποιούσε να μείνεις στην ίδια πόλη ή περιοχή για τα επόμενα 10 χρόνια;',
    lifestyle_q3: 'Νιώθεις συναισθηματικά «δεμένος/η» με το σπίτι ή τη γειτονιά σου;',
    lifestyle_q4: 'Θα προτιμούσες να μείνεις στην ίδια πόλη, ακόμη και αν υπήρχε οικονομικός ή επαγγελματικός λόγος να μετακινηθείς;',
    lifestyle_q5: 'Απαιτεί η δουλειά σου να βρίσκεσαι σταθερά στην περιοχή όπου ζεις σήμερα;',
    lifestyle_q6: 'Θα προτιμούσες να παραμείνεις στην τωρινή σου τοποθεσία, ακόμη και αν μπορούσες να δουλέψεις εξ αποστάσεως;',
    lifestyle_q7: 'Θα προτιμούσες να ζεις σε δικό σου σπίτι, ακόμη κι αν αυτό σημαίνει λιγότερη ευελιξία σε σχέση με το ενοίκιο;',
    lifestyle_q8: 'Είσαι διατεθειμένος/η να αναλάβεις το κόστος και τη φροντίδα για τη συντήρηση του σπιτιού σου;',
    lifestyle_q9: 'Πιστεύεις ότι ένα δικό σου σπίτι προσφέρει περισσότερη ασφάλεια και αξίζει την επένδυση;',
    lifestyle_q10: 'Θα προτιμούσες να μείνεις στο δικό σου σπίτι, ακόμη κι αν δεν είναι η πιο συμφέρουσα οικονομικά επιλογή;',
    lifestyleConclusion: 'Αξιολόγηση Lifestyle',
    lifestyleScoreBuying: 'Οι απαντήσεις σου δείχνουν ισχυρή προτίμηση για ιδιοκατοίκηση',
    lifestyleScoreRenting: 'Οι απαντήσεις σου δείχνουν ευελιξία και προτίμηση για ενοικίαση',
    lifestyleScoreNeutral: 'Οι απαντήσεις σου δείχνουν ισορροπημένη άποψη μεταξύ αγοράς και ενοικίασης',
    step2Title: 'Συλλογή Βασικών Οικονομικών Δεδομένων',
    step2Subtitle: 'Εισάγετε τα οικονομικά σας στοιχεία με ακρίβεια',
    financial_q1: 'Ποιο είναι το καθαρό μηνιαίο εισόδημά σου (μετά τους φόρους);',
    financial_q2: 'Ποιο είναι το τρέχον ή εκτιμώμενο μηνιαίο ενοίκιό σου;',
    financial_q3: 'Ποια είναι (ή ήταν) η συνολική τιμή αγοράς του ακινήτου;',
    financial_q4: 'Ποια θα ήταν/είναι η μηνιαία δόση δανείου;',
    financial_q5: 'Ποιό είναι το συνολικό εκτιμώμενο ετήσιο κόστος ιδιοκτησίας;',
    financial_q6: 'Ποιο θα ήταν το μηνιαίο ενοίκιο που θα μπορούσες να εισπράττεις;',
    financial_q7: 'Πόσα χρήματα ως αρχικό κεφάλαιο για την αγορά;',
    financial_q8: 'Πόσο μηνιαίο παθητικό εισόδημα λαμβάνεις;',
    step3Title: 'Αυτόματοι Υπολογισμοί & Δείκτες Σύγκρισης',
    step3Subtitle: 'Βάσει των στοιχείων σου, εδώ είναι οι βασικές μετρικές',
    indicator_1_title: 'Συνολικό Μηνιαίο Κόστος Ιδιοκατοίκησης',
    indicator_1_desc: 'Άθροισμα δόσης, συντήρησης, ασφάλισης, φόρων κτλ.',
    indicator_2_title: 'Μηνιαία Σύγκριση Κόστους Κατοικίας',
    indicator_2_desc: 'Αρνητικό = σε συμφέρει η ενοικίαση. Θετικό δεν σημαίνει πάντα ότι η αγορά είναι σοφότερη.',
    indicator_3_title: 'Ποσοστό Εισοδήματος για Στέγαση (Αγορά)',
    indicator_3_desc: 'Πάνω από 40% θεωρείται υψηλό οικονομικό βάρος.',
    indicator_4_title: 'Ποσοστό Εισοδήματος για Στέγαση (Ενοικίαση)',
    indicator_4_desc: 'Πάνω από 40% θεωρείται υψηλό οικονομικό βάρος.',
    indicator_5_title: 'Κέρδος/Ζημιά αν Ενοικιάσεις το Ιδιόκτητο',
    indicator_5_desc: 'Θετικό = το ενοίκιο ξεπερνά τα έξοδα, κερδίζεις.',
    indicator_6_title: 'Δείκτης Τιμής προς Ενοίκιο',
    indicator_6_desc: 'Χαμηλότερος είναι καλύτερος για αγορά. Πάνω από 20 = ευνοείται η ενοικίαση.',
    step4Title: 'Τελικό Συμπέρασμα',
    step4Subtitle: 'Ολοκληρωμένη ανάλυση βάσει όλων των δεδομένων',
    conclusion_1_title: 'Θα είχες καθαρό κέρδος αν ενοικίαζες το ιδιόκτητο;',
    conclusion_2_title: 'Ετήσια απόδοση % αν το εκμισθώσεις;',
    conclusion_3_title: 'Βάσει Δείκτη Τιμής/Ενοικίου, τι ευνοείται;',
    conclusion_4_title: 'Αν επένδυες το αρχικό κεφάλαιο σε 15% ετήσια για 10 χρόνια:',
    financialIndependenceRule: 'ΚΑΝΟΝΑΣ ΟΙΚΟΝΟΜΙΚΗΣ ΑΝΕΞΑΡΤΗΣΙΑΣ:',
    financialIndependenceRuleText: 'Αν το παθητικό εισόδημα δεν καλύπτει τα έξοδα ιδιοκτησίας, μην αγοράσεις για να μείνεις!',
    profitAnswer: 'Ναι, καθαρό μηνιαίο κέρδος €{amount}',
    lossAnswer: 'Όχι, μηνιαία ζημιά €{amount}',
    breakEvenAnswer: 'Ισοσκελισμένο',
    returnRate: '{rate}% ετήσια απόδοση',
    priceToRentConclusion: 'Δείκτης: {ratio} - {recommendation}',
    priceToRentFavorBuying: 'Ιδιοκατοίκηση πιο ευνοϊκή',
    priceToRentFavorRenting: 'Ενοικίαση πιο ευνοϊκή',
    priceToRentNeutral: 'Σχετικά ισορροπημένο',
    investmentProjection: '€{amount} (vs €{initial} αρχικό)',
    startOver: 'Επανεκκίνηση',
    
    // Old calculator keys (kept for backward compatibility if needed)
    propertyPrice: 'Τιμή Ακινήτου (€)',
    downPayment: 'Προκαταβολή (%)',
    interestRate: 'Επιτόκιο (%)',
    loanTerm: 'Διάρκεια Δανείου (έτη)',
    monthlyRent: 'Μηνιαίο Ενοίκιο (€)',
    annualAppreciation: 'Ετήσια Ανατίμηση Ακινήτου (%)',
    maintenanceCost: 'Ετήσιο Κόστος Συντήρησης (€)',
    propertyTax: 'Ετήσιος Φόρος Ακινήτου (€)',
    calculate: 'Υπολογισμός',
    reset: 'Επαναφορά',
    
    // Results
    resultsTitle: 'Αποτελέσματα Σύγκρισης',
    buyingOption: 'Αγορά',
    rentingOption: 'Ενοικίαση',
    monthlyPayment: 'Μηνιαία Δόση',
    totalCostYears: 'Συνολικό Κόστος ({years} έτη)',
    totalInterest: 'Σύνολο Τόκων',
    equity: 'Κεφάλαιο που Χτίζεται',
    totalRentPaid: 'Συνολικά Ενοίκια',
    propertyValue: 'Εκτιμώμενη Αξία Ακινήτου',
    netPosition: 'Καθαρή Οικονομική Θέση',
    recommendation: 'Σύσταση',
    buyingBetter: 'Η αγορά είναι πιο συμφέρουσα μακροπρόθεσμα',
    rentingBetter: 'Η ενοικίαση είναι πιο συμφέρουσα μακροπρόθεσμα',
    switchToDark: 'Αλλαγή σε σκοτεινό θέμα',
    switchToLight: 'Αλλαγή σε φωτεινό θέμα',
    openMenu: 'Άνοιγμα μενού',
    closeMenu: 'Κλείσιμο μενού',
    pageNotFound: 'Ωχ! Η σελίδα δεν βρέθηκε',
    pageNotFoundDesc: 'Η σελίδα που αναζητάτε δεν υπάρχει ή έχει μετακινηθεί.',
    returnHome: 'Επιστροφή στην Αρχική',
    servicesPageTitle: 'Δίπλα σου σε κάθε βήμα',
    servicesPageSubtitle: 'Εξασφαλίζουμε ομαλή και διαφανή διαδικασία, από τον έλεγχο μέχρι την ολοκλήρωση της συναλλαγής—χωρίς άγχος.',
    servicesPageTagline: 'Νομικός, τεχνικός και εμπορικός συντονισμός από ένα σημείο.',
    legalTechnicalCheckTitle: 'Νομικός & Τεχνικός έλεγχος',
    legalTechnicalCheckDesc: 'Ελέγχουμε τίτλους, τυχόν βάρη/εκκρεμότητες και την τεχνική/πολεοδομική κατάσταση, ώστε να γνωρίζεις ακριβώς τι αποκτάς.',
    legalTechnicalCheckFeature1: 'Έλεγχος τίτλων & βαρών (κτηματολόγιο/υποθηκοφυλακείο)',
    legalTechnicalCheckFeature2: 'Πολεοδομική συμμόρφωση & αυθαιρεσίες',
    legalTechnicalCheckFeature3: 'Σαφής αναφορά ευρημάτων & κινδύνων',
    propertyFolderTitle: 'Σύσταση φακέλου ακινήτου',
    propertyFolderDesc: 'Συγκεντρώνουμε και οργανώνουμε όλα τα έγγραφα (τίτλοι, Ε9, τακτοποιήσεις, Ενεργειακά Πιστοποιητικά κ.ά.) για γρήγορη και ασφαλή υπογραφή.',
    propertyFolderFeature1: 'Checklist δικαιολογητικών & προθεσμιών',
    propertyFolderFeature2: 'Ψηφιακή αρχειοθέτηση, έτοιμη για συμβολαιογράφο',
    propertyFolderFeature3: 'Παρακολούθηση εκκρεμοτήτων',
    valuationReportTitle: 'Έκθεση εκτίμησης ακινήτου',
    valuationReportDesc: 'Παρέχουμε τεκμηριωμένη αποτίμηση με συγκριτικά αγοράς και ανάλυση ζήτησης, για δίκαιη και ρεαλιστική τιμή.',
    valuationReportFeature1: 'Συγκριτικά real-time & ιστορικά δεδομένα',
    valuationReportFeature2: 'Ανάλυση περιοχής, ζήτησης & αποδόσεων',
    valuationReportFeature3: 'Διαφανής μεθοδολογία αποτίμησης',
    professionalPhotographyTitle: 'Υπηρεσία επαγγελματικής φωτογράφισης',
    professionalPhotographyDesc: 'Υψηλής ποιότητας φωτογράφιση (και προαιρετικά κάτοψη/staging) για κορυφαία παρουσίαση σε αγγελίες και social.',
    professionalPhotographyFeature1: 'HDR φωτογραφίες & σύντομο βίντεο/REELS',
    professionalPhotographyFeature2: 'Κάτοψη & light virtual staging (προαιρετικά)',
    professionalPhotographyFeature3: 'Βελτιστοποίηση για portals & social media',
    startNow: 'Ξεκίνα τώρα',
    talkToAdvisor: 'Μίλησε με σύμβουλο',
    requestValuation: 'Ζήτησε εκτίμηση',
    bookAppointment: 'Κλείσε ραντεβού',
    readyToStart: 'Έτοιμος να ξεκινήσεις; Ζήτησε μια προσαρμοσμένη προσφορά σήμερα.',
    requestQuote: 'Ζήτησε προσφορά',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
